"""
Truth Doc System — Feature specifications for Atlas Core.

Every feature has:
- Inputs (what user does)
- Expected output (what must happen)
- Failure behavior (what happens if it can't)
- Acceptance test (how you prove it works)
"""

TRUTH_DOC = {
    "version": "1.0.0",
    "doctrine": "Build → Prove → Lock",
    "last_updated": "2026-02-08",
    "features": [
        {
            "id": "FEAT-001",
            "name": "Persona Chat",
            "layer": "ui",
            "category": "core",
            "description": "Send messages to AI personas (Ajani, Minerva, Hermes) and receive responses",
            "inputs": "Select persona tab, type message, tap Send",
            "expected_output": "AI response appears in chat area within 15 seconds, styled with persona colors and identity badge",
            "failure_behavior": "API timeout → show 'Response delayed, retrying...' with retry button; API key missing → show setup instructions; Network down → show cached greeting + offline badge",
            "acceptance_test": "Send 10 messages to each persona sequentially; verify all responses arrive, are persona-appropriate, and display correctly on mobile + desktop",
            "release_stage": "beta",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": True,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-002",
            "name": "Trinity Counsel Mode",
            "layer": "app_logic",
            "category": "core",
            "description": "All three personas collaborate on a single request, providing multi-perspective analysis",
            "inputs": "Select Trinity tab, type complex question, tap Send",
            "expected_output": "Three-part response with each persona's analysis, clearly labeled and color-coded; synthesis conclusion at end",
            "failure_behavior": "One persona fails → show partial response from available personas with note; All fail → show error with retry; Timeout → progressive response (show each as they arrive)",
            "acceptance_test": "Send 5 complex questions requiring cross-domain analysis; verify all 3 personas respond with distinct perspectives and synthesis appears",
            "release_stage": "beta",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": False,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-003",
            "name": "Voice Mode (ElevenLabs TTS)",
            "layer": "service",
            "category": "multimedia",
            "description": "Read AI responses aloud using ElevenLabs text-to-speech",
            "inputs": "Tap Voice toggle to enable, send message or tap speaker icon on existing response",
            "expected_output": "Audio plays through device speaker; visual waveform indicator shows playback; auto-pauses if new message sent",
            "failure_behavior": "API key missing → show 'Voice requires ElevenLabs key' + setup link; Network down → show 'Voice unavailable offline' badge; Audio blocked → show browser permission prompt with instructions",
            "acceptance_test": "Enable voice, send 5 messages; verify audio plays, waveform shows, pause/resume works; test with mic permission denied; test offline",
            "release_stage": "alpha",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": True,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-004",
            "name": "Image Analysis (Blueprint Scanner)",
            "layer": "service",
            "category": "multimedia",
            "description": "Upload image for AI analysis — blueprints, designs, diagrams get phased build steps",
            "inputs": "Tap camera/upload icon, select image (file picker or camera), add optional prompt, select category, tap Analyze",
            "expected_output": "AI returns structured analysis with identified components, phased build steps, parts list; image thumbnail shows in chat",
            "failure_behavior": "Image too large → compress automatically + notify; Unsupported format → show supported formats list; Camera permission denied → fall back to file picker with instructions; API error → show partial analysis if available",
            "acceptance_test": "Upload 5 different image types (photo, diagram, blueprint, sketch, screenshot); verify analysis quality; test with camera permission denied; test with 10MB+ image",
            "release_stage": "alpha",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": False,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-005",
            "name": "Edge Panel (Research Lab)",
            "layer": "ui",
            "category": "research",
            "description": "Slide-out drawer showing 17 persona research projects with lifecycle indicators, progress bars, activity feed, and engineering specs",
            "inputs": "Tap edge handle on right side of screen to open panel; tap project card to expand; tap Engineering Specs to view detailed docs",
            "expected_output": "Panel slides in with smooth animation; 17 project cards with persona colors, progress %, phase indicators; scrollable activity feed; Design Philosophy doctrine visible at top",
            "failure_behavior": "Database empty → auto-seed on first open; API error → show cached last-known state; Slow load → show skeleton cards with pulse animation",
            "acceptance_test": "Open panel 10 times rapidly; verify smooth animation; check all 17 projects display; verify activity feed loads; test on mobile (touch drag) + desktop (click)",
            "release_stage": "beta",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": True,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-006",
            "name": "Engineering Specs Viewer",
            "layer": "ui",
            "category": "research",
            "description": "Detailed engineering documentation for each research project — modules, interfaces, failure modes, safety gates, block diagrams",
            "inputs": "Open Edge Panel → tap project card → tap 'Engineering Specs' button",
            "expected_output": "Modal displays with numbered module list, interface definitions, FMEA table, safety gate list, lifecycle, and ASCII block diagram; scrollable on mobile",
            "failure_behavior": "Specs not found → show 'Specs pending for this project' placeholder; Render error → show raw JSON fallback",
            "acceptance_test": "Open specs for all 17 projects; verify each has modules, interfaces, failure modes; test scroll on mobile; verify INSERT-CELL shows 8 subsystems and 9 FMEA modes",
            "release_stage": "beta",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": True,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-007",
            "name": "Conversation Memory",
            "layer": "data",
            "category": "core",
            "description": "Persist chat conversations across sessions with auto-save and history browsing",
            "inputs": "Chat normally — conversations auto-save; tap history icon to browse past conversations; tap conversation to resume",
            "expected_output": "Messages persist after page reload; conversation list shows title, persona, timestamp; resuming loads full message history",
            "failure_behavior": "Database unavailable → store in localStorage as fallback + sync when DB returns; Storage full → warn user + offer cleanup; Corrupt data → show recovery option",
            "acceptance_test": "Send 20 messages, reload page, verify all persist; test with 50+ conversations; test localStorage fallback by simulating DB down",
            "release_stage": "beta",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": True,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-008",
            "name": "Lesson Plan System",
            "layer": "app_logic",
            "category": "education",
            "description": "23-field curriculum with AI-evaluated tests, adaptive learning, study timers, and progress tracking",
            "inputs": "Select field of study → browse subfields → start chapter → study → take end-of-chapter test",
            "expected_output": "Chapter content delivered in 9-part lesson structure; progress bar updates; test generates 5-10 questions; AI evaluates answers with feedback; mastery score updates",
            "failure_behavior": "AI unavailable → show pre-cached lesson content without test; Test submission fails → save locally + retry; Progress sync fails → queue for background sync",
            "acceptance_test": "Complete full chapter in 3 different fields; verify progress persists; take test and verify AI evaluation; test offline lesson viewing",
            "release_stage": "alpha",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": False,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-009",
            "name": "Dragon-Scale Forge (Creative Canvas)",
            "layer": "service",
            "category": "creative",
            "description": "Web-based sketching and image processing tool with style packs and capsule system",
            "inputs": "Open Forge → select brush/tool → draw on canvas → apply style pack → export or save as capsule",
            "expected_output": "Responsive canvas with pressure-sensitive drawing; style packs apply filters/effects; capsules save state for later; export as PNG",
            "failure_behavior": "Canvas API unsupported → show compatibility message with alternatives; Save fails → auto-save to localStorage; Export fails → offer clipboard copy",
            "acceptance_test": "Draw on canvas with 5 different tools; apply 3 style packs; save and reload capsule; export image; test on touch + mouse devices",
            "release_stage": "alpha",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": True,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-010",
            "name": "Multi-Agent Orchestration",
            "layer": "service",
            "category": "core",
            "description": "Ajani plans, Minerva vetoes/approves, Hermes executes — full pipeline with memory and tool use",
            "inputs": "POST to /agents/ask with complex request requiring multi-step execution",
            "expected_output": "Ajani decomposes task → Minerva risk-checks → Hermes executes tools → Ajani verifies output → memory stores decisions",
            "failure_behavior": "Single agent fails → partial result with agent status; Tool execution fails → Hermes retries with alternative approach; Pipeline stalls → timeout with partial results + explanation",
            "acceptance_test": "Submit 5 multi-step requests; verify all 3 agents participate; verify memory stores outcomes; test with intentional tool failures",
            "release_stage": "alpha",
            "dod_status": {
                "real_device": False,
                "handles_permission_denied": True,
                "handles_offline": False,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-011",
            "name": "Hermes Router (3-Lane Task Routing)",
            "layer": "service",
            "category": "core",
            "description": "Routes tasks through FAST, SAFE, or HEAVY lanes based on complexity and risk assessment",
            "inputs": "POST to /hermes/route with task payload; system auto-classifies lane",
            "expected_output": "Task classified into correct lane; FAST lane returns in <2s; SAFE lane adds verification step; HEAVY lane shows progress updates",
            "failure_behavior": "Classification fails → default to SAFE lane; Lane overloaded → queue with position indicator; Timeout → escalate to next lane with explanation",
            "acceptance_test": "Route 20 tasks of varying complexity; verify correct lane assignment; measure FAST lane latency; verify SAFE lane verification step",
            "release_stage": "alpha",
            "dod_status": {
                "real_device": False,
                "handles_permission_denied": True,
                "handles_offline": False,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-012",
            "name": "Pre-Reality Engine (Simulation)",
            "layer": "service",
            "category": "simulation",
            "description": "Safety-gated educational simulation with BioSim, MachineSim, LightSim, SoundSim domains",
            "inputs": "POST to /simulation/run with scenario description + domain; SafetyGate validates",
            "expected_output": "Simulation results with confidence score, persona annotations, safety gate pass/fail status; visual output for applicable domains",
            "failure_behavior": "SafetyGate blocks → clear refusal message with explanation; Domain unavailable → suggest alternative domain; Simulation timeout → partial results with confidence warning",
            "acceptance_test": "Run 3 simulations per domain; verify SafetyGate blocks harmful scenarios; verify confidence scores are reasonable; test timeout handling",
            "release_stage": "alpha",
            "dod_status": {
                "real_device": False,
                "handles_permission_denied": True,
                "handles_offline": False,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-013",
            "name": "UWS Workshop Manual Generator",
            "layer": "service",
            "category": "creative",
            "description": "AI-powered build manual generator following 10 UWS Laws with LEGO-style micro-steps",
            "inputs": "Describe project to build → select difficulty → AI generates step-by-step manual with visuals",
            "expected_output": "HTML flipbook manual with numbered steps, parts lists, checkpoint markers, progress tracking; follows build-before-explain principle",
            "failure_behavior": "AI unavailable → show template manual structure; Generation timeout → show first completed steps + continue button; Invalid project → suggest alternatives",
            "acceptance_test": "Generate manuals for 5 different project types; verify all 10 UWS Laws followed; test flipbook navigation; verify checkpoints track correctly",
            "release_stage": "alpha",
            "dod_status": {
                "real_device": False,
                "handles_permission_denied": True,
                "handles_offline": False,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-014",
            "name": "Chameleon Protocol (Privacy Shield)",
            "layer": "service",
            "category": "security",
            "description": "Defensive privacy doctrine with threat model T0-T4 and persona-specific response tiers",
            "inputs": "POST to /doctrine/chameleon with threat level assessment request",
            "expected_output": "Threat classification (T0-T4), recommended actions per persona (Hermes: technical, Minerva: guardian, Ajani: strategic), actionable checklist",
            "failure_behavior": "Classification uncertain → default to higher threat level (safe side); API down → show offline safety checklist; Invalid input → request clarification with examples",
            "acceptance_test": "Submit 5 scenarios at different threat levels; verify correct classification; verify persona-specific recommendations; test escalation from T0 to T4",
            "release_stage": "alpha",
            "dod_status": {
                "real_device": False,
                "handles_permission_denied": True,
                "handles_offline": False,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-015",
            "name": "Notification System",
            "layer": "ui",
            "category": "system",
            "description": "Push notification bell with unread count, notification types, and dismissal",
            "inputs": "Tap bell icon → view notifications → tap to act → dismiss or mark read",
            "expected_output": "Badge count shows unread; dropdown lists notifications by type (research update, lesson reminder, system alert); tapping navigates to relevant section",
            "failure_behavior": "Push API unavailable → fall back to in-app polling; Permission denied → show in-app only with explanation; Too many notifications → group by type with count",
            "acceptance_test": "Trigger 10 notifications of different types; verify badge count; verify dismiss/mark-read; test with notification permission denied; test rapid fire (20 in 5 seconds)",
            "release_stage": "alpha",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": True,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-016",
            "name": "Private Mode (Incognito)",
            "layer": "app_logic",
            "category": "security",
            "description": "Toggle private mode — conversations not saved, no history, auto-clear on exit",
            "inputs": "Tap Private toggle in status bar → eye icon appears → chat normally → toggle off to return to normal",
            "expected_output": "Visual indicator (eye icon, dimmed UI) shows private mode active; messages not persisted; exiting private mode clears all session data; no trace in conversation history",
            "failure_behavior": "Toggle fails → show error + keep current mode; Accidental data save in private → auto-purge on next load; Mode state lost on crash → default to non-private (safe)",
            "acceptance_test": "Enable private mode, send 10 messages, reload page → verify zero messages persisted; toggle on/off 5 times rapidly; test crash recovery",
            "release_stage": "alpha",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": True,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-017",
            "name": "System Status Dashboard",
            "layer": "ui",
            "category": "system",
            "description": "Real-time system health display — online status, clock, fingerprint, version badge",
            "inputs": "Always visible in status bar; auto-updates every 30 seconds",
            "expected_output": "Green dot + 'System Online' when healthy; date/time display; version badge; fingerprint hash for build verification",
            "failure_behavior": "Backend unreachable → red dot + 'System Offline' + timestamp of last contact; Clock drift → sync on reconnect; Version mismatch → show update indicator",
            "acceptance_test": "Verify status bar shows correct state; kill backend → verify offline indicator within 60s; restart → verify recovery; check clock accuracy",
            "release_stage": "beta",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": True,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
        {
            "id": "FEAT-018",
            "name": "Theme Switcher",
            "layer": "ui",
            "category": "system",
            "description": "Switch between visual themes — dark default, moody atmospheric variants",
            "inputs": "Tap theme icon in header area → select from available themes",
            "expected_output": "Smooth CSS transition to new theme; preference saved in localStorage; applies to all UI components including Edge Panel",
            "failure_behavior": "Theme data corrupt → fall back to default dark theme; localStorage unavailable → use default (no save); Transition jank → disable animation fallback",
            "acceptance_test": "Switch through all themes 5 times; reload page → verify preference persists; test with localStorage disabled; verify Edge Panel theme consistency",
            "release_stage": "alpha",
            "dod_status": {
                "real_device": True,
                "handles_permission_denied": True,
                "handles_offline": True,
                "handles_repeated_use": True,
                "has_test": False,
                "logs_errors": True,
            },
        },
    ],
}


ARCHITECTURE_LAYERS = {
    "ui": {
        "name": "UI Layer",
        "description": "Screens, buttons, animations, visual components",
        "rule": "UI never talks to the database or hardware directly. It calls services.",
        "components": ["index.html", "Edge Panel", "Status Bar", "Chat Interface", "Theme System", "Notification Bell"],
    },
    "app_logic": {
        "name": "App Logic Layer",
        "description": "State management, workflows, routing — what happens when you tap",
        "rule": "Pure logic, no side effects. Takes input, returns decisions.",
        "components": ["PersonaKernel", "ResponsePipeline", "TrinityMode", "PrivateMode", "TaskRouter"],
    },
    "service": {
        "name": "Service Layer",
        "description": "Audio recorder, storage, AI calls, auth, BLE, simulation, generation",
        "rule": "Each service owns one concern. Services can call other services but never the UI.",
        "components": ["VoicePipeline", "ImagePipeline", "MultimodalRouter", "HermesRouter", "AgentOrchestrator", "PreRealityEngine", "UWSGenerator", "DragonScaleForge", "ChameleonProtocol"],
    },
    "data": {
        "name": "Data Layer",
        "description": "Database models, caching, syncing, persistence",
        "rule": "Single source of truth. All reads/writes go through ORM. No raw SQL in app code.",
        "components": ["SQLAlchemy Models", "Session Manager", "ResearchTracker", "ConversationStore", "ProgressTracker"],
    },
}


RELEASE_STAGES = {
    "alpha": {
        "name": "Alpha",
        "description": "Internal testing only — you and the system",
        "gate_criteria": [
            "Feature compiles and runs without crash",
            "Basic happy path works",
            "Error messages display (not silent failures)",
            "Logged in observability system",
        ],
    },
    "beta": {
        "name": "Beta",
        "description": "Trusted testers — stable enough for real use",
        "gate_criteria": [
            "All Alpha criteria met",
            "Definition of Done checklist: 4+ items checked",
            "Handles offline / slow network",
            "Handles repeated use (10x in a row)",
            "No data loss on crash or reload",
            "Tested on real mobile device",
        ],
    },
    "release": {
        "name": "Release",
        "description": "Ship-ready — proven reliable",
        "gate_criteria": [
            "All Beta criteria met",
            "Full Definition of Done checklist passed",
            "Has at least one automated test",
            "Tested on Chrome + Safari + mobile browser",
            "Observability events firing correctly",
            "No known critical bugs",
        ],
    },
}


DESIGN_PHILOSOPHY = {
    "doctrine": "Build → Prove → Lock",
    "principles": [
        {
            "id": "P1",
            "name": "Freeze Before Build",
            "rule": "Define inputs, outputs, failure behavior, and acceptance test BEFORE writing code",
        },
        {
            "id": "P2",
            "name": "4-Layer Separation",
            "rule": "UI → App Logic → Services → Data. No layer may skip. UI never touches the database.",
        },
        {
            "id": "P3",
            "name": "Refusal by Design",
            "rule": "Every risky feature gets a fallback chain: no internet → cached mode, API down → retry + status, permission denied → guide user, storage full → warn + cleanup",
        },
        {
            "id": "P4",
            "name": "Provable Functions",
            "rule": "A feature is not done until it passes the 6-point Definition of Done checklist",
        },
        {
            "id": "P5",
            "name": "Ship in Stages",
            "rule": "Alpha (you only) → Beta (trusted testers) → Release (wider users). Each stage has a bug list + fixes before moving on.",
        },
        {
            "id": "P6",
            "name": "Observe Everything",
            "rule": "Structured logs, crash reporting, analytics events for key actions. If you can't see failures, you can't fix them fast.",
        },
    ],
    "definition_of_done": [
        "Works on real device (not just emulator)",
        "Handles permission denied",
        "Handles offline / slow internet",
        "Handles repeated use (10 times in a row)",
        "Has at least one test",
        "Logs errors clearly",
    ],
}
