/* eslint-disable */
import React, { useEffect, useMemo, useState } from 'react';
import { BookOpen, Search, Loader2, RefreshCw, ExternalLink, GraduationCap, MessageCircle, Sparkles } from 'lucide-react';
import './KnowledgeBookshelf.css';
const BACKEND=process.env.REACT_APP_BACKEND_URL;
const SUBJECT_COLORS=['#b23a48','#386641','#31587a','#7b2cbf','#bc6c25','#2a9d8f','#9b2226','#5f6f52','#3a5a40','#6d597a','#457b9d','#8d6e63'];
const PERSONAS=[{id:'ajani',label:'Ask Ajani',color:'#F03246'},{id:'minerva',label:'Ask Minerva',color:'#28C8BE'},{id:'hermes',label:'Ask Hermes',color:'#F4EFE4'}];
const list=(d,k=[])=>{if(Array.isArray(d))return d;for(const x of k)if(Array.isArray(d?.[x]))return d[x];return[]};
const sid=s=>String(s?.id||s?.slug||s?.name||s||'').toLowerCase();
const sname=s=>s?.name||s?.label||s?.title||s;
export default function KnowledgeBookshelf({aiColor,initialSubject=null}){
 const [subjects,setSubjects]=useState([]),[resources,setResources]=useState([]),[subject,setSubject]=useState(initialSubject?sid(initialSubject):'all'),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[reloadKey,setReloadKey]=useState(0);
 useEffect(()=>{if(initialSubject)setSubject(sid(initialSubject));},[initialSubject]);
 useEffect(()=>{let c=false;setLoading(true);setError('');Promise.all([fetch(`${BACKEND}/api/kbase/subjects`).then(async r=>{if(!r.ok)throw Error(`subjects ${r.status}`);return r.json()}),fetch(`${BACKEND}/api/kbase/resources`).then(async r=>{if(!r.ok)throw Error(`resources ${r.status}`);return r.json()})]).then(([a,b])=>{if(!c){setSubjects(list(a,['subjects','items','data']));setResources(list(b,['resources','items','data']))}}).catch(e=>!c&&setError(e.message||'Knowledge Bank unavailable')).finally(()=>!c&&setLoading(false));return()=>{c=true}},[reloadKey]);
 const color=v=>{const k=String(v||'atlas').toLowerCase();let h=0;for(let i=0;i<k.length;i++)h=((h<<5)-h)+k.charCodeAt(i);return SUBJECT_COLORS[Math.abs(h)%SUBJECT_COLORS.length]},rs=r=>String(r.subject||r.subject_id||r.domain||'General');
 const filtered=useMemo(()=>resources.filter(r=>{const h=`${r.title||''} ${r.author||''} ${r.summary||''} ${r.source||''}`.toLowerCase();return(subject==='all'||rs(r).toLowerCase()===subject)&&(!query.trim()||h.includes(query.trim().toLowerCase()))}),[resources,subject,query]);
 const ask=p=>window.dispatchEvent(new CustomEvent('atlas-knowledge-question',{detail:{persona:p,resource:selected}})),teach=()=>window.dispatchEvent(new CustomEvent('atlas-teach-resource',{detail:{resource:selected}}));
 if(selected){const a=color(rs(selected));return <div className="knowledge-bookshelf kb-reading-room"><button className="bp-btn" onClick={()=>setSelected(null)}>← Return to bookshelf</button><article className="kb-open-book" style={{'--subject-accent':a}}><section className="kb-page kb-page-left"><div className="kb-bookmark"/><div className="kb-kicker">{rs(selected)}</div><div className="kb-detail-type">{selected.type||selected.resource_type||'KNOWLEDGE RESOURCE'}</div><h2>{selected.title||'Untitled resource'}</h2>{selected.author&&<div className="kb-byline">by {selected.author}</div>}<div className="kb-source-seal">ATLAS VERIFIED SOURCE</div></section><section className="kb-page kb-page-right"><h3>Research Notes</h3><p>{selected.summary||selected.description||'No summary is available yet. ATLAS can research this resource further.'}</p><div className="kb-meta">Source: {selected.source||selected.provider||'ATLAS Knowledge Bank'}</div><div className="kb-reader-actions"><button className="kb-action primary" onClick={teach} style={{borderColor:aiColor}}><GraduationCap size={13}/> Teach Me</button>{PERSONAS.map(p=><button key={p.id} className="kb-action" onClick={()=>ask(p.id)} style={{borderColor:p.color,color:p.color}}><MessageCircle size={12}/> {p.label}</button>)}{selected.url&&<a className="kb-action" href={selected.url} target="_blank" rel="noreferrer"><ExternalLink size={12}/> Open source</a>}</div><div className="kb-action-note"><Sparkles size={11}/> Connected through the HUD event bus.</div></section></article></div>}
 return <div className="knowledge-bookshelf"><div className="kb-header"><div><div className="kb-kicker">{initialSubject?`${sname(initialSubject)} LIBRARY`:'ATLAS RESEARCH ARCHIVE'}</div><h3 style={{color:aiColor}}><BookOpen size={15}/> Knowledge Bookshelf</h3><p>{initialSubject?`Resources classified under ${sname(initialSubject)}.`:'Twenty-two disciplines organized as a living engineering library.'}</p></div><button className="bp-btn" onClick={()=>setReloadKey(n=>n+1)}><RefreshCw size={12}/></button></div><label className="kb-search"><Search size={13}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search this library…"/></label><div className="kb-subject-tabs"><button className={`kb-tab ${subject==='all'?'active':''}`} onClick={()=>setSubject('all')}>ALL SHELVES</button>{subjects.map(s=>{const id=sid(s),c=color(id);return <button key={id} className={`kb-tab ${subject===id?'active':''}`} onClick={()=>setSubject(id)} style={{'--tab-color':c,...(subject===id?{borderColor:c,color:c}:{})}}><span className="kb-tab-mark"/>{sname(s)}</button>})}</div>{loading&&<div className="kb-state"><Loader2 size={15} className="spin"/> Loading Knowledge Bank…</div>}{!loading&&error&&<div className="kb-state kb-error">Knowledge Bank unavailable: {error}</div>}{!loading&&!error&&filtered.length===0&&<div className="kb-state">No resources match this shelf yet.</div>}{!loading&&!error&&filtered.length>0&&<div className="kb-library-wall">{filtered.map((r,i)=><button key={r.id||r.resource_id||`${r.title}-${i}`} className="kb-volume" onClick={()=>setSelected(r)} style={{'--book-accent':color(rs(r))}}><span className="kb-volume-band"/><span className="kb-volume-type">{r.type||r.resource_type||'REFERENCE'}</span><strong>{r.title||'Untitled resource'}</strong><span className="kb-volume-author">{r.author||r.provider||rs(r)}</span><span className="kb-volume-subject">{rs(r)}</span></button>)}</div>}<div className="kb-footer">{filtered.length} volume{filtered.length===1?'':'s'}</div></div>;
}
