/* eslint-disable */
import React,{useEffect,useMemo,useState}from'react';import{ChevronLeft,ChevronRight,Library,Sparkles,Loader2}from'lucide-react';import'./KnowledgeCurriculum.css';
const BACKEND=process.env.REACT_APP_BACKEND_URL;
const FALLBACK_SUBJECTS=['Aerospace','Architecture','AI','Biology','Business','Chemistry','Creative Writing','Economics','Electronics','Environmental Science','Film Studies','Game Design','History','Mathematics','Music Theory','Nanotechnology','Philosophy','Physics','Psychology','Robotics','Software Engineering','Visual Arts'];
const nameOf=s=>s?.name||s?.label||s?.title||s,idOf=s=>String(s?.id||s?.slug||nameOf(s)||'').toLowerCase(),norm=v=>String(v||'').trim().toLowerCase();
export default function KnowledgeCurriculum({subjects=[],aiColor,onEnterSubject}){const list=subjects.length?subjects:FALLBACK_SUBJECTS,[index,setIndex]=useState(0),[mastery,setMastery]=useState([]),[masteryLoading,setMasteryLoading]=useState(true),[masteryError,setMasteryError]=useState('');
useEffect(()=>{let c=false;setMasteryLoading(true);fetch(`${BACKEND}/api/learning/mastery?limit=200`).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.detail||`mastery ${r.status}`);return d}).then(d=>{if(!c)setMastery(Array.isArray(d.best_per_topic)?d.best_per_topic:[])}).catch(e=>{if(!c)setMasteryError(e.message||'Mastery unavailable')}).finally(()=>{if(!c)setMasteryLoading(false)});return()=>{c=true}},[]);
const active=list[index]||list[0],activeName=nameOf(active),activeId=idOf(active),move=d=>setIndex(i=>(i+d+list.length)%list.length),visible=[-3,-2,-1,0,1,2,3].map(offset=>({offset,item:list[(index+offset+list.length)%list.length]}));
const subjectMastery=useMemo(()=>{const exact=mastery.filter(m=>norm(m.topic)===norm(activeName));const related=exact.length?exact:mastery.filter(m=>norm(m.topic).includes(norm(activeName))||norm(activeName).includes(norm(m.topic)));if(!related.length)return null;const best=related.reduce((a,m)=>(Number(m.best_score||0)>Number(a.best_score||0)?m:a),related[0]);return{score:Number(best.best_score||0),rank:best.best_rank||'Aware',teacher:best.ai_owner||'council',attempt:best.last_attempt||'',topics:related.length}},[mastery,activeName]);
return <div className="kc-shell" data-testid="knowledge-curriculum"><div className="kc-topline"><span>ATLAS KNOWLEDGE CURRICULUM</span><span>{index+1} / {list.length}</span></div><div className="kc-stage"><button className="kc-arrow left" onClick={()=>move(-1)} aria-label="Previous subject"><ChevronLeft/></button><div className="kc-orbit" aria-label="Subject selector">{visible.map(({offset,item})=><button key={`${idOf(item)}-${offset}`} className={`kc-orbit-item ${offset===0?'active':''}`} style={{'--offset':offset}} onClick={()=>setIndex((index+offset+list.length)%list.length)}>{nameOf(item)}</button>)}</div><main className="kc-graffiti-zone"><div className="kc-spray-cloud"/><div className="kc-graffiti-shadow" aria-hidden="true">{activeName}</div><div className="kc-graffiti" data-subject={activeId}>{activeName}</div><div className="kc-stencil"><Sparkles size={12}/> SUBJECT IDENTITY // {activeId.toUpperCase()}</div><button className="kc-enter" onClick={()=>onEnterSubject(active)} style={{borderColor:aiColor,color:aiColor}}><Library size={14}/> ENTER {activeName.toUpperCase()} LIBRARY</button></main><aside className="kc-mastery"><div className="kc-mastery-title">MASTERY PROFILE</div>{masteryLoading?<div className="kc-note"><Loader2 size={11} className="spin"/> Loading learning record…</div>:subjectMastery?<><div className="kc-score-ring"><span>{subjectMastery.score}</span><small>{subjectMastery.rank.toUpperCase()}</small></div><div className="kc-metric"><div><span>Best quiz mastery</span><b>{subjectMastery.score}</b></div><div className="kc-meter"><i style={{width:`${subjectMastery.score}%`}}/></div></div><div className="kc-metric"><div><span>Rank</span><b>{subjectMastery.rank}</b></div></div><div className="kc-metric"><div><span>Lead AI</span><b>{subjectMastery.teacher}</b></div></div><div className="kc-note">Live mastery from ATLAS learning records · {subjectMastery.topics} matched topic{subjectMastery.topics===1?'':'s'}.</div></>:<><div className="kc-score-ring"><span>—</span><small>UNTESTED</small></div><div className="kc-note">{masteryError?`Learning record unavailable: ${masteryError}`:'No mastery assessment exists for this subject yet. Complete a lesson quiz to establish a real score.'}</div></>}</aside><button className="kc-arrow right" onClick={()=>move(1)} aria-label="Next subject"><ChevronRight/></button></div></div>}
