/* eslint-disable */
import React, { useEffect, useState } from 'react';
import { Loader2, Hammer, Check, Play, Pause, Archive } from 'lucide-react';

const BACKEND = process.env.REACT_APP_BACKEND_URL;

const STATUS_ICON = {
  proposed:    <Hammer size={11} />,
  in_progress: <Play size={11} />,
  completed:   <Check size={11} />,
  archived:    <Archive size={11} />,
};
const STATUS_LABEL = {
  proposed: 'Proposed',
  in_progress: 'In progress',
  completed: 'Completed',
  archived: 'Archived',
};
const STATUS_ORDER = ['proposed', 'in_progress', 'completed', 'archived'];

/**
 * ProjectsPanel — drives the outer-ring PROJECTS tile. Lists projects
 * auto-generated by the intake pipeline (one per lesson) plus any
 * manual ones, with status transitions.
 */
export default function ProjectsPanel({ aiColor }) {
  const [projects, setProjects] = useState([]);
  const [statusFilter, setStatusFilter] = useState('all');
  const [loading, setLoading] = useState(true);
  const [expanded, setExpanded] = useState(null);

  const load = async () => {
    try {
      const url = statusFilter === 'all'
        ? `${BACKEND}/api/learning/projects?limit=80`
        : `${BACKEND}/api/learning/projects?limit=80&status=${statusFilter}`;
      const res = await fetch(url);
      const data = await res.json();
      setProjects(data.items || []);
    } catch (_) { /* network */ }
    setLoading(false);
  };

  useEffect(() => { load(); /* eslint-disable-next-line */ }, [statusFilter]);

  const cycleStatus = async (project) => {
    const cur = STATUS_ORDER.indexOf(project.status || 'proposed');
    const next = STATUS_ORDER[(cur + 1) % STATUS_ORDER.length];
    try {
      const res = await fetch(`${BACKEND}/api/learning/projects/${project.id}/status`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ status: next }),
      });
      if (res.ok) load();
    } catch (_) { /* network */ }
  };

  return (
    <div className="bp-workbench" data-testid="projects-panel">
      <h3 className="bp-title" style={{ color: aiColor }}><Hammer size={14} /> Projects</h3>
      <p className="bp-help">
        Hands-on projects auto-generated from your lessons. Tap the status pill to cycle:
        proposed → in progress → completed → archived.
      </p>

      <div className="bp-actions" data-testid="projects-filters">
        {['all', ...STATUS_ORDER].map((s) => (
          <button
            key={s}
            className={`bp-btn ${statusFilter === s ? 'primary' : ''}`}
            onClick={() => setStatusFilter(s)}
            data-testid={`projects-filter-${s}`}
            style={statusFilter === s ? { borderColor: aiColor, color: aiColor } : undefined}
          >
            {s === 'all' ? 'All' : STATUS_LABEL[s]}
          </button>
        ))}
      </div>

      {loading && <div className="bp-section"><Loader2 size={14} className="spin" /> Loading projects…</div>}

      {!loading && projects.length === 0 && (
        <div className="bp-section" data-testid="projects-empty">
          No projects yet. Use EXPLORE to ingest a lesson — the lead AI will propose a project automatically.
        </div>
      )}

      {!loading && projects.map((p) => (
        <div
          key={p.id}
          className={`project-card ${expanded === p.id ? 'expanded' : ''}`}
          data-testid={`project-card-${p.id}`}
          style={{ borderLeftColor: p.ai_owner ? `var(--ai-${p.ai_owner})` : aiColor }}
        >
          <div className="project-card-head" onClick={() => setExpanded(expanded === p.id ? null : p.id)}>
            <div className="project-card-title">{p.title}</div>
            <button
              className="project-status-pill"
              onClick={(e) => { e.stopPropagation(); cycleStatus(p); }}
              data-testid={`project-status-${p.id}`}
              style={{ color: aiColor, borderColor: aiColor }}
            >
              {STATUS_ICON[p.status || 'proposed']}
              {STATUS_LABEL[p.status || 'proposed']}
            </button>
          </div>
          <div className="project-card-summary">{p.summary}</div>
          {expanded === p.id && (
            <div className="project-card-body">
              {p.steps?.length > 0 && (
                <div>
                  <div className="project-card-label">Steps</div>
                  <ol className="project-card-list">
                    {p.steps.map((s, i) => <li key={i}>{s}</li>)}
                  </ol>
                </div>
              )}
              {p.materials?.length > 0 && (
                <div>
                  <div className="project-card-label">Materials</div>
                  <ul className="project-card-list">
                    {p.materials.map((m, i) => <li key={i}>{m}</li>)}
                  </ul>
                </div>
              )}
              {p.expected_outcome && (
                <div>
                  <div className="project-card-label">Expected outcome</div>
                  <div className="bp-voice-body">{p.expected_outcome}</div>
                </div>
              )}
              <div className="project-card-meta">
                Owner: <strong style={{ color: aiColor }}>{(p.ai_owner || 'council').toUpperCase()}</strong>
                {p.topic && <> · Topic: {p.topic}</>}
              </div>
            </div>
          )}
        </div>
      ))}
    </div>
  );
}
