/* eslint-disable */
import React, { useEffect, useMemo, useState } from 'react';
import { Loader2, BookOpen, Beaker } from 'lucide-react';
import { useAtlasJob } from '../../hooks/useAtlasJob';
import InteractiveSandbox, { pickLabForTopic } from './InteractiveSandbox';

const BAND_META={simple:{label:'Simple understanding',color:'#9CD3FF'},systems:{label:'Systems understanding',color:'#28C8BE'},advanced:{label:'Advanced understanding',color:'#F03246'},speculative:{label:'Speculative / Research',color:'#B388FF'}};
function splitLesson(markdown){if(!markdown)return{};const sections={},re=/^###\s+(SIMPLE|SYSTEMS|ADVANCED|SPECULATIVE)\b\s*$/gim,indices=[];let match;while((match=re.exec(markdown))!==null)indices.push({name:match[1].toLowerCase(),start:match.index,headerLen:match[0].length});for(let i=0;i<indices.length;i++){const cur=indices[i],next=indices[i+1];sections[cur.name]=markdown.slice(cur.start+cur.headerLen,next?next.start:markdown.length).trim()}return sections}
function topicFromResource(resource){if(!resource)return'';const subject=resource.subject||resource.subject_id||resource.domain||'';const title=resource.title||resource.name||'';const summary=resource.summary||resource.description||'';return [subject,title,summary?`Source context: ${summary}`:''].filter(Boolean).join(' — ')}

export default function TeachingWorkbench({aiColor,forceSandbox=false}){
 const [topic,setTopic]=useState(''),[sandboxOpen,setSandboxOpen]=useState(Boolean(forceSandbox)),[sandboxLab,setSandboxLab]=useState('power');
 const job=useAtlasJob();const busy=job.status==='pending'||job.status==='running',lesson=job.status==='done'?job.result:null,matchedLab=useMemo(()=>pickLabForTopic(topic),[topic]);
 useEffect(()=>{if(lesson&&matchedLab){setSandboxLab(matchedLab);setSandboxOpen(true)}},[lesson,matchedLab]);
 useEffect(()=>{const handler=e=>{const resource=e?.detail?.resource;if(!resource)return;const nextTopic=topicFromResource(resource);setTopic(nextTopic);if(nextTopic)job.run('/api/atlas/teach',{topic:nextTopic})};window.addEventListener('atlas-teach-resource',handler);return()=>window.removeEventListener('atlas-teach-resource',handler)},[job]);
 const onTeach=()=>{if(topic.trim())job.run('/api/atlas/teach',{topic})};
 const toggleSandbox=()=>setSandboxOpen(open=>{if(!open&&matchedLab)setSandboxLab(matchedLab);return!open});
 const sections=lesson?.lesson?splitLesson(lesson.lesson):{};
 return <div className="bp-workbench" data-testid="teaching-workbench"><h3 className="bp-title">Teaching Engine</h3><p className="bp-help">Type any subject, or send a resource here from the Knowledge Bookshelf. The council selects the right lead core and returns four nested learning depths.</p><textarea className="bp-textarea" value={topic} onChange={e=>setTopic(e.target.value)} placeholder="e.g. How do enzymes work? · Select Teach Me from a Knowledge Book" rows={3} data-testid="teach-topic-input"/><div className="bp-actions"><button className="bp-btn primary" style={{borderColor:aiColor,color:aiColor}} onClick={onTeach} disabled={!topic.trim()||busy} data-testid="teach-btn">{busy?<Loader2 size={14} className="spin"/>:<BookOpen size={14}/>}Teach Me</button><button className={`bp-btn ${sandboxOpen?'primary':''}`} onClick={toggleSandbox} data-testid="teach-sandbox-toggle" style={sandboxOpen?{borderColor:aiColor,color:aiColor}:undefined}><Beaker size={14}/>{sandboxOpen?'Close hands-on lab':'Try a hands-on lab'}</button></div>{busy&&<div className="bp-section bp-loading">{job.status==='pending'?'Submitting job…':'The teaching engine is working · 30–90 seconds.'}</div>}{job.status==='failed'&&<div className="bp-error">Teaching job failed: {job.error}</div>}{lesson&&!lesson.error&&<div className="bp-section" data-testid="teach-output"><h4>Taught by {lesson.teacher?.toUpperCase()}{lesson.lead_via_council?' · selected by council':''}</h4>{Object.keys(BAND_META).map(b=>{const body=sections[b];if(!body)return null;const meta=BAND_META[b];return <details key={b} className="bp-phase" open={b==='simple'}><summary style={{color:meta.color}}>{meta.label}</summary><div className="bp-voice-body">{body}</div></details>})}{Object.keys(sections).length===0&&<div className="bp-voice-body">{lesson.lesson}</div>}</div>}{lesson?.error&&<div className="bp-error">{lesson.error}</div>}{sandboxOpen&&<div className="bp-section bp-sandbox-wrap" data-testid="teach-sandbox-wrap"><InteractiveSandbox initialLabKey={sandboxLab} topic={topic}/></div>}</div>;
}
