"""
Blueprint Handbook Generator — Visual SVG-based build manuals for Atlas Core projects.
Generates flipbook-style pages with schematic diagrams, parts layouts, and assembly steps.
"""

from typing import Optional

HANDBOOK_CONFIGS = {
    "insert-cell": {
        "title": "INSERT-CELL Universal Power Platform",
        "subtitle": "Modular Energy Source Docking System",
        "cover_color": "#ff4444",
        "pages": [
            {
                "page": 1,
                "type": "cover",
                "title": "INSERT-CELL",
                "subtitle": "Universal Power Spine Construction",
                "version": "v1.0",
                "classification": "PROTOTYPE BUILD",
            },
            {
                "page": 2,
                "type": "overview",
                "title": "System Overview",
                "desc": "The INSERT-CELL platform accepts any compliant energy source through a universal dock. Power is negotiated, isolated, converted, buffered, and monitored before delivery to the load.",
                "diagram": {
                    "type": "block_flow",
                    "blocks": [
                        {"id": "DOCK", "label": "Universal\nDock", "x": 50, "y": 120, "w": 100, "h": 60, "color": "#ff4444"},
                        {"id": "ISO", "label": "Isolation\nShell", "x": 200, "y": 120, "w": 100, "h": 60, "color": "#ff6666"},
                        {"id": "CONV", "label": "Conversion\nLayer", "x": 350, "y": 120, "w": 100, "h": 60, "color": "#ff8888"},
                        {"id": "BUF", "label": "Buffer\nPack", "x": 500, "y": 120, "w": 100, "h": 60, "color": "#ffaaaa"},
                        {"id": "NEG", "label": "Power\nNegotiator", "x": 125, "y": 240, "w": 100, "h": 50, "color": "#cc3333"},
                        {"id": "TEL", "label": "Telemetry\nRing", "x": 275, "y": 240, "w": 100, "h": 50, "color": "#cc5555"},
                        {"id": "SAFE", "label": "Hermes\nSafe Kernel", "x": 425, "y": 240, "w": 100, "h": 50, "color": "#993333"},
                    ],
                    "arrows": [
                        {"from": "DOCK", "to": "ISO", "label": "raw power"},
                        {"from": "ISO", "to": "CONV", "label": "isolated"},
                        {"from": "CONV", "to": "BUF", "label": "conditioned"},
                        {"from": "NEG", "to": "DOCK", "label": "identity", "style": "dashed"},
                        {"from": "TEL", "to": "SAFE", "label": "health"},
                    ],
                },
            },
            {
                "page": 3,
                "type": "parts_layout",
                "title": "Parts Layout — Exploded View",
                "desc": "All components laid out in assembly order. Each part is numbered and cross-referenced with the parts list.",
                "parts": [
                    {"id": "P1", "name": "Docking Base Plate", "spec": "Aluminum 6061-T6, 200x150x8mm", "x": 300, "y": 260, "w": 250, "h": 30, "color": "#888"},
                    {"id": "P2", "name": "Energy Interface Module", "spec": "10A rated, gold-plated contacts", "x": 130, "y": 200, "w": 80, "h": 40, "color": "#ff4444"},
                    {"id": "P3", "name": "Energy Interface Module", "spec": "10A rated, gold-plated contacts", "x": 340, "y": 200, "w": 80, "h": 40, "color": "#ff4444"},
                    {"id": "P4", "name": "Power Distribution Board", "spec": "4-way, 20A rated", "x": 220, "y": 140, "w": 120, "h": 50, "color": "#44aa44"},
                    {"id": "P5", "name": "Microcontroller Unit", "spec": "Arduino compatible, 16MHz", "x": 380, "y": 140, "w": 80, "h": 50, "color": "#4444ff"},
                    {"id": "P6", "name": "Voltage Regulator", "spec": "Buck converter, 3-24V output", "x": 200, "y": 70, "w": 90, "h": 35, "color": "#ff8800"},
                    {"id": "P7", "name": "Isolation Barrier", "spec": "Galvanic isolation, 2.5kV rated", "x": 330, "y": 70, "w": 100, "h": 35, "color": "#aa44aa"},
                    {"id": "P8", "name": "Thermal Sensor Array", "spec": "4x NTC thermistors, -40 to 125°C", "x": 470, "y": 140, "w": 80, "h": 50, "color": "#44aaaa"},
                    {"id": "P9", "name": "Buffer Capacitor Bank", "spec": "4x 1000µF, 35V electrolytic", "x": 470, "y": 70, "w": 80, "h": 35, "color": "#aaaa44"},
                    {"id": "P10", "name": "Protective Shell", "spec": "ABS enclosure, IP54 rated", "x": 250, "y": 10, "w": 200, "h": 30, "color": "#666"},
                ],
            },
            {
                "page": 4,
                "type": "assembly_step",
                "title": "Step 1: Prepare Docking Base",
                "step_number": 1,
                "instruction": "Secure the aluminum base plate to your workbench using clamps. Mark mounting hole positions at 30mm from each edge. Drill 4x M4 mounting holes. Deburr all edges.",
                "tools": ["Drill press or hand drill", "M4 drill bit", "Deburring tool", "Bench clamps", "Center punch"],
                "safety": "Wear safety glasses when drilling. Secure workpiece before drilling.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 150, "y": 120, "w": 350, "h": 80, "color": "#888", "label": "Base Plate"},
                        {"shape": "circle", "x": 190, "y": 140, "r": 6, "color": "#ff4444", "label": "M4"},
                        {"shape": "circle", "x": 460, "y": 140, "r": 6, "color": "#ff4444", "label": "M4"},
                        {"shape": "circle", "x": 190, "y": 180, "r": 6, "color": "#ff4444", "label": "M4"},
                        {"shape": "circle", "x": 460, "y": 180, "r": 6, "color": "#ff4444", "label": "M4"},
                        {"shape": "dimension", "x1": 150, "y1": 220, "x2": 500, "y2": 220, "label": "200mm"},
                        {"shape": "dimension", "x1": 120, "y1": 120, "x2": 120, "y2": 200, "label": "150mm"},
                    ],
                },
                "checkpoint": "Base plate is flat, holes are clean, no burrs. All 4 holes accept M4 bolts freely.",
            },
            {
                "page": 5,
                "type": "assembly_step",
                "title": "Step 2: Mount Energy Interface Modules",
                "step_number": 2,
                "instruction": "Install two Energy Interface Modules on opposite sides of the base plate. Align gold contacts facing upward. Secure with M3 screws (4 per module). Apply thermal compound between module base and plate.",
                "tools": ["M3 screwdriver", "Thermal compound", "Torque wrench (0.5 Nm)"],
                "safety": "Do not overtighten — max torque 0.5 Nm. Thermal compound is non-toxic but avoid skin contact.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 150, "y": 160, "w": 350, "h": 80, "color": "#888", "label": "Base Plate"},
                        {"shape": "rect", "x": 170, "y": 130, "w": 80, "h": 40, "color": "#ff4444", "label": "Interface L"},
                        {"shape": "rect", "x": 400, "y": 130, "w": 80, "h": 40, "color": "#ff4444", "label": "Interface R"},
                        {"shape": "arrow_down", "x": 210, "y": 110, "len": 20, "color": "#ffaa00"},
                        {"shape": "arrow_down", "x": 440, "y": 110, "len": 20, "color": "#ffaa00"},
                    ],
                },
                "checkpoint": "Both modules seated flush. Contacts face up. No thermal compound on contacts. Screws at 0.5 Nm.",
            },
            {
                "page": 6,
                "type": "assembly_step",
                "title": "Step 3: Install Power Distribution Board",
                "step_number": 3,
                "instruction": "Mount the Power Distribution Board centrally on the base plate using 4x M3 standoffs (10mm height). Connect power input traces to both Energy Interface Modules using 14AWG silicone wire.",
                "tools": ["M3 standoffs (10mm)", "Soldering iron", "14AWG silicone wire", "Wire strippers"],
                "safety": "Soldering iron reaches 350°C. Use fume extraction. Verify no shorts before proceeding.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 150, "y": 180, "w": 350, "h": 80, "color": "#888", "label": "Base Plate"},
                        {"shape": "rect", "x": 170, "y": 150, "w": 80, "h": 40, "color": "#ff4444", "label": "Interface L"},
                        {"shape": "rect", "x": 400, "y": 150, "w": 80, "h": 40, "color": "#ff4444", "label": "Interface R"},
                        {"shape": "rect", "x": 270, "y": 110, "w": 120, "h": 50, "color": "#44aa44", "label": "Power Dist Board"},
                        {"shape": "wire", "x1": 250, "y1": 160, "x2": 270, "y2": 135, "color": "#ff0"},
                        {"shape": "wire", "x1": 400, "y1": 160, "x2": 390, "y2": 135, "color": "#ff0"},
                    ],
                },
                "checkpoint": "Board level on standoffs. Both power connections soldered. Continuity test passes. No shorts to ground.",
            },
            {
                "page": 7,
                "type": "assembly_step",
                "title": "Step 4: Add Microcontroller & Sensors",
                "step_number": 4,
                "instruction": "Mount the MCU adjacent to the Power Distribution Board on a separate standoff. Wire I2C bus (SDA/SCL) to thermal sensor array. Connect analog inputs to voltage monitoring points on the distribution board.",
                "tools": ["Soldering iron", "26AWG signal wire", "Multimeter"],
                "safety": "Static-sensitive components. Use ESD wrist strap.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 150, "y": 180, "w": 350, "h": 80, "color": "#888", "label": "Base Plate"},
                        {"shape": "rect", "x": 270, "y": 120, "w": 120, "h": 50, "color": "#44aa44", "label": "Power Dist"},
                        {"shape": "rect", "x": 410, "y": 120, "w": 80, "h": 50, "color": "#4444ff", "label": "MCU"},
                        {"shape": "rect", "x": 510, "y": 120, "w": 60, "h": 50, "color": "#44aaaa", "label": "Sensors"},
                        {"shape": "wire", "x1": 390, "y1": 145, "x2": 410, "y2": 145, "color": "#0f0"},
                        {"shape": "wire", "x1": 490, "y1": 145, "x2": 510, "y2": 145, "color": "#0ff"},
                    ],
                },
                "checkpoint": "MCU powers on via USB. I2C scan detects 4 thermal sensors. Voltage readings within 5% of multimeter.",
            },
            {
                "page": 8,
                "type": "assembly_step",
                "title": "Step 5: Install Isolation & Conversion",
                "step_number": 5,
                "instruction": "Mount the galvanic isolation barrier between the dock input and the conversion layer. Install the buck converter module. Wire high-side through isolation barrier, low-side to buffer capacitor bank.",
                "tools": ["Soldering iron", "12AWG power wire", "Isolation tester"],
                "safety": "Isolation barrier rated 2.5kV — verify isolation resistance before connecting load side.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 100, "y": 140, "w": 100, "h": 50, "color": "#ff4444", "label": "Dock Input"},
                        {"shape": "rect", "x": 230, "y": 140, "w": 100, "h": 50, "color": "#aa44aa", "label": "Isolation"},
                        {"shape": "rect", "x": 360, "y": 140, "w": 100, "h": 50, "color": "#ff8800", "label": "Converter"},
                        {"shape": "rect", "x": 490, "y": 140, "w": 80, "h": 50, "color": "#aaaa44", "label": "Buffer"},
                        {"shape": "wire", "x1": 200, "y1": 165, "x2": 230, "y2": 165, "color": "#f00"},
                        {"shape": "wire", "x1": 330, "y1": 165, "x2": 360, "y2": 165, "color": "#ff0"},
                        {"shape": "wire", "x1": 460, "y1": 165, "x2": 490, "y2": 165, "color": "#0f0"},
                    ],
                },
                "checkpoint": "Isolation resistance > 100MΩ. Converter output voltage matches setting. Buffer charges to target within 5 seconds.",
            },
            {
                "page": 9,
                "type": "wiring",
                "title": "Wiring Diagram",
                "desc": "Complete wiring overview showing all power and signal connections between modules.",
                "connections": [
                    {"from": "Dock L", "to": "Isolation In", "type": "power", "gauge": "14AWG", "color": "#ff0000"},
                    {"from": "Dock R", "to": "Isolation In", "type": "power", "gauge": "14AWG", "color": "#ff0000"},
                    {"from": "Isolation Out", "to": "Converter In", "type": "power", "gauge": "12AWG", "color": "#ff8800"},
                    {"from": "Converter Out", "to": "Buffer +", "type": "power", "gauge": "12AWG", "color": "#00cc00"},
                    {"from": "Buffer -", "to": "GND Bus", "type": "power", "gauge": "12AWG", "color": "#000000"},
                    {"from": "MCU SDA", "to": "Sensor SDA", "type": "signal", "gauge": "26AWG", "color": "#00aaff"},
                    {"from": "MCU SCL", "to": "Sensor SCL", "type": "signal", "gauge": "26AWG", "color": "#00aaff"},
                    {"from": "MCU A0-A3", "to": "Dist Board Mon", "type": "signal", "gauge": "26AWG", "color": "#aa00ff"},
                    {"from": "Dist Board", "to": "Load Output", "type": "power", "gauge": "10AWG", "color": "#00cc00"},
                ],
            },
            {
                "page": 10,
                "type": "final_assembly",
                "title": "Final Assembly & Testing",
                "desc": "Close the enclosure, perform final checks, and run acceptance tests.",
                "checklist": [
                    {"item": "All solder joints inspected — no cold joints or bridges", "critical": True},
                    {"item": "Isolation resistance test passed (>100MΩ)", "critical": True},
                    {"item": "Thermal sensors responding on I2C bus", "critical": False},
                    {"item": "Power negotiation protocol handshake successful", "critical": True},
                    {"item": "Output voltage within ±2% of target under load", "critical": True},
                    {"item": "Thermal runaway protection triggers at 85°C", "critical": True},
                    {"item": "Enclosure sealed to IP54 standard", "critical": False},
                    {"item": "All cable strain reliefs installed", "critical": False},
                    {"item": "Label applied with serial number and build date", "critical": False},
                ],
            },
        ],
    },

    "hydra-core": {
        "title": "HYDRA-CORE Hydrogen Fuel Cell Engine",
        "subtitle": "PEM Fuel Cell Stack Assembly",
        "cover_color": "#00cc88",
        "pages": [
            {
                "page": 1,
                "type": "cover",
                "title": "HYDRA-CORE",
                "subtitle": "Hydrogen Fuel Cell Engine Assembly",
                "version": "v1.0",
                "classification": "PROTOTYPE BUILD",
            },
            {
                "page": 2,
                "type": "overview",
                "title": "System Overview",
                "desc": "The HYDRA-CORE converts hydrogen gas into electrical power through a PEM (Proton Exchange Membrane) fuel cell stack. Water is the only byproduct. The system includes hydrogen input, micro-cell lattice, thermal management, water recycling, and INSERT-CELL dock interface.",
                "diagram": {
                    "type": "block_flow",
                    "blocks": [
                        {"id": "H2IN", "label": "H₂ Input\nLayer", "x": 50, "y": 100, "w": 100, "h": 60, "color": "#00cc88"},
                        {"id": "CELL", "label": "Micro-Cell\nLattice", "x": 200, "y": 100, "w": 110, "h": 60, "color": "#00aa66"},
                        {"id": "THERM", "label": "Thermal\nReclaimer", "x": 200, "y": 210, "w": 110, "h": 50, "color": "#ff6644"},
                        {"id": "H2O", "label": "Water\nFeedback", "x": 360, "y": 210, "w": 100, "h": 50, "color": "#4488ff"},
                        {"id": "DOCK", "label": "INSERT-CELL\nDock", "x": 360, "y": 100, "w": 110, "h": 60, "color": "#ffaa00"},
                        {"id": "CTRL", "label": "Hybrid Buffer\nController", "x": 510, "y": 150, "w": 110, "h": 50, "color": "#aa44ff"},
                    ],
                    "arrows": [
                        {"from": "H2IN", "to": "CELL", "label": "H₂ feed"},
                        {"from": "CELL", "to": "DOCK", "label": "DC output"},
                        {"from": "CELL", "to": "H2O", "label": "water"},
                        {"from": "THERM", "to": "CELL", "label": "cooling"},
                        {"from": "H2O", "to": "CELL", "label": "humidity"},
                        {"from": "CTRL", "to": "H2IN", "label": "flow cmd"},
                    ],
                },
            },
            {
                "page": 3,
                "type": "parts_layout",
                "title": "Parts Layout — Exploded View",
                "desc": "Complete parts inventory arranged in assembly order from bottom (structural) to top (functional).",
                "parts": [
                    {"id": "P1", "name": "Structural Frame", "spec": "316L stainless steel, 300x200x12mm", "x": 270, "y": 270, "w": 260, "h": 25, "color": "#888"},
                    {"id": "P2", "name": "PEM Membrane Assembly", "spec": "Nafion 212, 5-cell stack", "x": 300, "y": 220, "w": 200, "h": 35, "color": "#00cc88"},
                    {"id": "P3", "name": "Bipolar Plates", "spec": "Graphite composite, flow channels", "x": 310, "y": 170, "w": 180, "h": 30, "color": "#666"},
                    {"id": "P4", "name": "Gas Diffusion Layers", "spec": "Carbon paper, PTFE-treated", "x": 320, "y": 130, "w": 160, "h": 25, "color": "#444"},
                    {"id": "P5", "name": "H₂ Pressure Regulator", "spec": "0-10 bar, stainless diaphragm", "x": 120, "y": 200, "w": 100, "h": 40, "color": "#00aa66"},
                    {"id": "P6", "name": "Coolant Pump", "spec": "12V DC, 5L/min, brushless", "x": 120, "y": 130, "w": 100, "h": 40, "color": "#ff6644"},
                    {"id": "P7", "name": "Water Collection Tank", "spec": "HDPE, 500mL capacity", "x": 520, "y": 200, "w": 80, "h": 40, "color": "#4488ff"},
                    {"id": "P8", "name": "DC-DC Converter", "spec": "Boost converter, 12-48V output", "x": 520, "y": 130, "w": 80, "h": 40, "color": "#ffaa00"},
                    {"id": "P9", "name": "Control Board", "spec": "STM32-based, CAN bus interface", "x": 350, "y": 70, "w": 100, "h": 35, "color": "#aa44ff"},
                ],
            },
            {
                "page": 4,
                "type": "assembly_step",
                "title": "Step 1: Prepare Structural Frame",
                "step_number": 1,
                "instruction": "Clean the stainless steel frame with isopropyl alcohol. Install 8x M5 threaded inserts at marked positions. Mount 4x rubber isolation feet on the underside.",
                "tools": ["Thread insert tool", "Isopropyl alcohol", "Rubber feet (4x)", "M5 threaded inserts (8x)"],
                "safety": "Stainless edges may be sharp. Wear cut-resistant gloves during handling.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 150, "y": 140, "w": 350, "h": 60, "color": "#888", "label": "Steel Frame"},
                        {"shape": "circle", "x": 180, "y": 215, "r": 8, "color": "#444", "label": "foot"},
                        {"shape": "circle", "x": 310, "y": 215, "r": 8, "color": "#444", "label": "foot"},
                        {"shape": "circle", "x": 340, "y": 215, "r": 8, "color": "#444", "label": "foot"},
                        {"shape": "circle", "x": 470, "y": 215, "r": 8, "color": "#444", "label": "foot"},
                    ],
                },
                "checkpoint": "Frame clean and dry. All 8 threaded inserts flush. Feet level — frame does not rock on flat surface.",
            },
            {
                "page": 5,
                "type": "assembly_step",
                "title": "Step 2: Stack PEM Membrane Assembly",
                "step_number": 2,
                "instruction": "Layer the 5-cell PEM stack: anode GDL → bipolar plate → membrane → cathode GDL → bipolar plate. Repeat for all 5 cells. Align using guide pins. Apply even compression using torque sequence.",
                "tools": ["Clean room gloves", "Torque wrench (2 Nm)", "Alignment pins", "Compression plates"],
                "safety": "Nafion membrane is moisture-sensitive. Work in low-humidity environment. Do not touch active area with bare hands.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 200, "y": 80, "w": 250, "h": 15, "color": "#666", "label": "Top Plate"},
                        {"shape": "rect", "x": 200, "y": 100, "w": 250, "h": 10, "color": "#444", "label": "GDL"},
                        {"shape": "rect", "x": 200, "y": 115, "w": 250, "h": 12, "color": "#00cc88", "label": "Membrane"},
                        {"shape": "rect", "x": 200, "y": 132, "w": 250, "h": 10, "color": "#444", "label": "GDL"},
                        {"shape": "rect", "x": 200, "y": 147, "w": 250, "h": 15, "color": "#666", "label": "Bipolar Plate"},
                        {"shape": "rect", "x": 200, "y": 167, "w": 250, "h": 10, "color": "#444", "label": "GDL"},
                        {"shape": "rect", "x": 200, "y": 182, "w": 250, "h": 12, "color": "#00cc88", "label": "Membrane"},
                        {"shape": "rect", "x": 200, "y": 199, "w": 250, "h": 10, "color": "#444", "label": "GDL"},
                        {"shape": "rect", "x": 200, "y": 214, "w": 250, "h": 15, "color": "#666", "label": "Bottom Plate"},
                    ],
                },
                "checkpoint": "All layers aligned within 0.5mm. Compression uniform — no bulging. Guide pins seat fully.",
            },
            {
                "page": 6,
                "type": "assembly_step",
                "title": "Step 3: Install H₂ Input System",
                "step_number": 3,
                "instruction": "Mount the pressure regulator on the frame inlet side. Connect H₂ supply line using Swagelok fittings. Install check valve downstream of regulator. Connect regulated output to cell stack manifold.",
                "tools": ["Swagelok wrenches", "PTFE tape", "Leak detection fluid", "Tube cutter"],
                "safety": "HYDROGEN IS FLAMMABLE. Ensure ventilation. No ignition sources. Leak-test all connections with soapy water before pressurizing.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 80, "y": 140, "w": 60, "h": 40, "color": "#00cc88", "label": "H₂ Tank"},
                        {"shape": "rect", "x": 180, "y": 140, "w": 80, "h": 40, "color": "#00aa66", "label": "Regulator"},
                        {"shape": "rect", "x": 300, "y": 140, "w": 50, "h": 40, "color": "#44aa44", "label": "Check\nValve"},
                        {"shape": "rect", "x": 400, "y": 120, "w": 160, "h": 80, "color": "#00cc88", "label": "Cell Stack\nManifold"},
                        {"shape": "wire", "x1": 140, "y1": 160, "x2": 180, "y2": 160, "color": "#0f0"},
                        {"shape": "wire", "x1": 260, "y1": 160, "x2": 300, "y2": 160, "color": "#0f0"},
                        {"shape": "wire", "x1": 350, "y1": 160, "x2": 400, "y2": 160, "color": "#0f0"},
                    ],
                },
                "checkpoint": "No leaks at any fitting under 5 bar test pressure. Regulator output stable at set pressure.",
            },
            {
                "page": 7,
                "type": "wiring",
                "title": "Electrical Wiring Diagram",
                "desc": "All electrical connections from cell stack to INSERT-CELL dock interface.",
                "connections": [
                    {"from": "Cell Stack +", "to": "DC-DC In +", "type": "power", "gauge": "10AWG", "color": "#ff0000"},
                    {"from": "Cell Stack -", "to": "DC-DC In -", "type": "power", "gauge": "10AWG", "color": "#000000"},
                    {"from": "DC-DC Out +", "to": "Dock Power +", "type": "power", "gauge": "10AWG", "color": "#00cc00"},
                    {"from": "DC-DC Out -", "to": "Dock Power -", "type": "power", "gauge": "10AWG", "color": "#000000"},
                    {"from": "Control CAN_H", "to": "Dock CAN_H", "type": "signal", "gauge": "22AWG", "color": "#00aaff"},
                    {"from": "Control CAN_L", "to": "Dock CAN_L", "type": "signal", "gauge": "22AWG", "color": "#00aaff"},
                    {"from": "Temp Sensors", "to": "Control ADC", "type": "signal", "gauge": "26AWG", "color": "#ff8800"},
                    {"from": "Coolant Pump", "to": "Control PWM", "type": "signal", "gauge": "22AWG", "color": "#aa00ff"},
                ],
            },
            {
                "page": 8,
                "type": "final_assembly",
                "title": "Final Assembly & Commissioning",
                "desc": "Complete system validation before first hydrogen test.",
                "checklist": [
                    {"item": "All H₂ fittings leak-tested at 5 bar with detection fluid", "critical": True},
                    {"item": "PEM stack compression within spec (2.0 Nm ± 0.1)", "critical": True},
                    {"item": "Coolant loop filled and bled — no air pockets", "critical": True},
                    {"item": "H₂ sensor responds to calibration gas", "critical": True},
                    {"item": "Emergency shutoff valve functions mechanically", "critical": True},
                    {"item": "DC-DC converter output matches target voltage", "critical": False},
                    {"item": "CAN bus communication established with dock", "critical": False},
                    {"item": "Water collection drain path clear", "critical": False},
                    {"item": "All cables secured with strain relief", "critical": False},
                ],
            },
        ],
    },

    "green-robotics": {
        "title": "GREEN ROBOTICS Fleet Program",
        "subtitle": "Eco-Sentinel Biomimetic Machine Fleet",
        "cover_color": "#44cc44",
        "pages": [
            {
                "page": 1,
                "type": "cover",
                "title": "GREEN ROBOTICS",
                "subtitle": "Eco-Sentinel Fleet — 5 Machine Classes",
                "version": "v1.0",
                "classification": "DESIGN HANDBOOK",
            },
            {
                "page": 2,
                "type": "overview",
                "title": "Fleet Overview",
                "desc": "Five biomimetic machine classes designed to heal ecosystems. Each class has a specific ecological role, unique form factor, and shared Charter Kernel for safety enforcement.",
                "diagram": {
                    "type": "block_flow",
                    "blocks": [
                        {"id": "GRAZ", "label": "GRAZER\nSoil Restore", "x": 30, "y": 80, "w": 100, "h": 60, "color": "#8B4513"},
                        {"id": "TALL", "label": "TALLNECK\nSurvey Tower", "x": 155, "y": 80, "w": 100, "h": 60, "color": "#DAA520"},
                        {"id": "WATCH", "label": "WATCHER\nMonitor", "x": 280, "y": 80, "w": 100, "h": 60, "color": "#228B22"},
                        {"id": "AQUA", "label": "AQUATIC\nWater Clean", "x": 405, "y": 80, "w": 100, "h": 60, "color": "#4488ff"},
                        {"id": "AERO", "label": "AERIAL\nAtmos Sample", "x": 530, "y": 80, "w": 100, "h": 60, "color": "#87CEEB"},
                        {"id": "MESH", "label": "HIVE MESH\nNetwork", "x": 155, "y": 200, "w": 110, "h": 50, "color": "#44cc44"},
                        {"id": "CHART", "label": "CHARTER\nKERNEL", "x": 310, "y": 200, "w": 110, "h": 50, "color": "#ff4444"},
                        {"id": "ENERGY", "label": "HYBRID\nENERGY", "x": 465, "y": 200, "w": 110, "h": 50, "color": "#ffaa00"},
                    ],
                    "arrows": [
                        {"from": "GRAZ", "to": "MESH", "label": "soil data"},
                        {"from": "TALL", "to": "MESH", "label": "survey"},
                        {"from": "WATCH", "to": "MESH", "label": "alerts"},
                        {"from": "AQUA", "to": "MESH", "label": "water"},
                        {"from": "AERO", "to": "MESH", "label": "atmos"},
                        {"from": "CHART", "to": "GRAZ", "label": "charter", "style": "dashed"},
                    ],
                },
            },
            {
                "page": 3,
                "type": "machine_profile",
                "title": "GRAZER — Soil Processing Unit",
                "machine_class": "grazer",
                "form_factor": "Quadrupedal, bovine-inspired chassis",
                "dimensions": "1.2m L × 0.8m W × 0.9m H",
                "weight": "85 kg operational",
                "power": "Solar + LiFePO₄ battery, 400Wh capacity",
                "speed": "0.5 m/s walking, 0.1 m/s tilling",
                "endurance": "8 hours continuous operation",
                "sensors": ["Soil pH probe", "Moisture sensor", "NPK analyzer", "Ground-penetrating radar", "GPS/RTK"],
                "tools": ["Rotary tiller attachment", "Seed dispenser (6 channels)", "Soil core sampler", "Mulch spreader"],
                "diagram": {
                    "type": "machine_schematic",
                    "body_shape": "quadruped",
                    "components": [
                        {"name": "Solar Panel Array", "position": "top", "x": 250, "y": 50, "w": 160, "h": 20, "color": "#4444cc"},
                        {"name": "Main Chassis", "position": "center", "x": 230, "y": 80, "w": 200, "h": 80, "color": "#8B4513"},
                        {"name": "Battery Pack", "position": "center", "x": 260, "y": 100, "w": 60, "h": 30, "color": "#ffaa00"},
                        {"name": "Control Unit", "position": "center", "x": 350, "y": 100, "w": 50, "h": 30, "color": "#44cc44"},
                        {"name": "Front Left Leg", "position": "leg", "x": 240, "y": 165, "w": 20, "h": 60, "color": "#666"},
                        {"name": "Front Right Leg", "position": "leg", "x": 310, "y": 165, "w": 20, "h": 60, "color": "#666"},
                        {"name": "Rear Left Leg", "position": "leg", "x": 350, "y": 165, "w": 20, "h": 60, "color": "#666"},
                        {"name": "Rear Right Leg", "position": "leg", "x": 410, "y": 165, "w": 20, "h": 60, "color": "#666"},
                        {"name": "Tiller Attachment", "position": "bottom", "x": 270, "y": 230, "w": 120, "h": 25, "color": "#aa4444"},
                        {"name": "Seed Dispenser", "position": "rear", "x": 390, "y": 140, "w": 40, "h": 20, "color": "#44aa44"},
                        {"name": "Soil Sensors", "position": "front", "x": 230, "y": 140, "w": 30, "h": 20, "color": "#aaaa44"},
                    ],
                },
            },
            {
                "page": 4,
                "type": "machine_profile",
                "title": "TALLNECK — Mobile Survey Tower",
                "machine_class": "tallneck",
                "form_factor": "Bipedal, giraffe-inspired elevated platform",
                "dimensions": "2.0m L × 1.2m W × 8.0m H (mast extended)",
                "weight": "350 kg operational",
                "power": "Solar + LiFePO₄ + wind turbine, 2kWh capacity",
                "speed": "0.3 m/s walking",
                "endurance": "72 hours stationary survey, 12 hours walking",
                "sensors": ["LIDAR (360°, 200m range)", "Multispectral camera (12 bands)", "Weather station (temp/humidity/wind/pressure)", "Mesh relay antenna (5km range)", "Seismometer"],
                "tools": ["Retractable mast (2-8m)", "Ground anchor deployment", "Mesh relay amplifier"],
                "diagram": {
                    "type": "machine_schematic",
                    "body_shape": "bipedal_tall",
                    "components": [
                        {"name": "Sensor Head", "position": "top", "x": 300, "y": 10, "w": 60, "h": 30, "color": "#DAA520"},
                        {"name": "LIDAR Ring", "position": "top", "x": 290, "y": 40, "w": 80, "h": 10, "color": "#ff4444"},
                        {"name": "Mast Section", "position": "center", "x": 320, "y": 55, "w": 20, "h": 100, "color": "#888"},
                        {"name": "Mesh Antenna", "position": "side", "x": 345, "y": 70, "w": 40, "h": 10, "color": "#44cc44"},
                        {"name": "Weather Station", "position": "side", "x": 275, "y": 70, "w": 40, "h": 10, "color": "#4488ff"},
                        {"name": "Body/Core", "position": "center", "x": 280, "y": 160, "w": 100, "h": 50, "color": "#DAA520"},
                        {"name": "Solar Canopy", "position": "top", "x": 260, "y": 145, "w": 140, "h": 12, "color": "#4444cc"},
                        {"name": "Battery Bank", "position": "center", "x": 290, "y": 175, "w": 40, "h": 25, "color": "#ffaa00"},
                        {"name": "Left Leg", "position": "leg", "x": 290, "y": 215, "w": 25, "h": 70, "color": "#666"},
                        {"name": "Right Leg", "position": "leg", "x": 345, "y": 215, "w": 25, "h": 70, "color": "#666"},
                        {"name": "Ground Anchor", "position": "bottom", "x": 305, "y": 290, "w": 50, "h": 15, "color": "#444"},
                    ],
                },
            },
            {
                "page": 5,
                "type": "machine_profile",
                "title": "WATCHER — Environmental Monitor",
                "machine_class": "watcher",
                "form_factor": "Compact raptor-inspired perching unit",
                "dimensions": "0.4m L × 0.3m W × 0.35m H",
                "weight": "5 kg",
                "power": "Solar + LiFePO₄, 50Wh capacity",
                "speed": "Stationary (repositioned by Tallneck or human)",
                "endurance": "30 days continuous monitoring",
                "sensors": ["360° optical camera array (4K)", "Air quality sensor (PM2.5, CO₂, O₃, NO₂)", "Acoustic ecology microphone", "Wildlife detection AI processor", "Temperature/humidity"],
                "tools": ["Perching clamp (tree/pole mount)", "Mesh relay node"],
                "diagram": {
                    "type": "machine_schematic",
                    "body_shape": "compact",
                    "components": [
                        {"name": "Camera Dome", "position": "top", "x": 295, "y": 80, "w": 70, "h": 30, "color": "#228B22"},
                        {"name": "Solar Panel", "position": "top", "x": 280, "y": 70, "w": 100, "h": 8, "color": "#4444cc"},
                        {"name": "Main Body", "position": "center", "x": 290, "y": 115, "w": 80, "h": 50, "color": "#228B22"},
                        {"name": "AI Processor", "position": "center", "x": 300, "y": 125, "w": 30, "h": 15, "color": "#44cc44"},
                        {"name": "Air Sensor", "position": "side", "x": 375, "y": 125, "w": 25, "h": 20, "color": "#aaaa44"},
                        {"name": "Microphone", "position": "side", "x": 260, "y": 125, "w": 25, "h": 20, "color": "#ff8800"},
                        {"name": "Battery", "position": "center", "x": 310, "y": 145, "w": 40, "h": 15, "color": "#ffaa00"},
                        {"name": "Perching Clamp", "position": "bottom", "x": 300, "y": 170, "w": 60, "h": 25, "color": "#666"},
                    ],
                },
            },
            {
                "page": 6,
                "type": "machine_profile",
                "title": "AQUATIC — Waterway Remediation Unit",
                "machine_class": "aquatic",
                "form_factor": "Semi-submersible manta-form platform",
                "dimensions": "2.5m wingspan × 1.5m L × 0.4m H",
                "weight": "120 kg",
                "power": "Solar + LiFePO₄ + water turbine, 600Wh",
                "speed": "0.8 m/s cruising, 0.2 m/s filtering",
                "endurance": "48 hours continuous filtering",
                "sensors": ["Water chemistry lab (pH, DO, turbidity, conductivity)", "Microplastic particle counter", "Flow rate sensor", "Underwater camera", "Temperature array"],
                "tools": ["Passive filtration membrane array", "Dissolved oxygen injector", "Microplastic collector basket", "Water sampling port"],
                "diagram": {
                    "type": "machine_schematic",
                    "body_shape": "manta",
                    "components": [
                        {"name": "Solar Surface", "position": "top", "x": 220, "y": 100, "w": 220, "h": 10, "color": "#4444cc"},
                        {"name": "Left Wing", "position": "wing", "x": 180, "y": 115, "w": 100, "h": 40, "color": "#4488ff"},
                        {"name": "Main Body", "position": "center", "x": 280, "y": 115, "w": 100, "h": 50, "color": "#4488ff"},
                        {"name": "Right Wing", "position": "wing", "x": 380, "y": 115, "w": 100, "h": 40, "color": "#4488ff"},
                        {"name": "Filter Array", "position": "bottom", "x": 230, "y": 170, "w": 200, "h": 20, "color": "#44aaaa"},
                        {"name": "O₂ Injector", "position": "rear", "x": 390, "y": 170, "w": 30, "h": 15, "color": "#00ff88"},
                        {"name": "Water Lab", "position": "center", "x": 290, "y": 130, "w": 50, "h": 20, "color": "#aaaa44"},
                        {"name": "Collector Basket", "position": "bottom", "x": 270, "y": 195, "w": 120, "h": 15, "color": "#888"},
                        {"name": "Propulsion", "position": "rear", "x": 200, "y": 155, "w": 30, "h": 20, "color": "#666"},
                    ],
                },
            },
            {
                "page": 7,
                "type": "machine_profile",
                "title": "AERIAL — Atmospheric Sampling Drone",
                "machine_class": "aerial",
                "form_factor": "Fixed-wing dragonfly-hybrid design",
                "dimensions": "1.8m wingspan × 0.6m L × 0.15m H",
                "weight": "8 kg",
                "power": "LiFePO₄ battery, 200Wh capacity",
                "speed": "15 m/s cruising, 25 m/s max",
                "endurance": "4 hours flight time",
                "sensors": ["Particulate collector (PM1, PM2.5, PM10)", "Gas chromatography module", "Wind profiler (3-axis)", "GPS/INS navigation", "Barometric altimeter"],
                "tools": ["Sample collection cartridges (6x)", "Emergency parachute", "GPS recovery beacon"],
                "diagram": {
                    "type": "machine_schematic",
                    "body_shape": "fixed_wing",
                    "components": [
                        {"name": "Left Wing", "position": "wing", "x": 160, "y": 120, "w": 140, "h": 25, "color": "#87CEEB"},
                        {"name": "Fuselage", "position": "center", "x": 295, "y": 110, "w": 70, "h": 35, "color": "#87CEEB"},
                        {"name": "Right Wing", "position": "wing", "x": 360, "y": 120, "w": 140, "h": 25, "color": "#87CEEB"},
                        {"name": "Sensor Nose", "position": "front", "x": 275, "y": 115, "w": 25, "h": 20, "color": "#aaaa44"},
                        {"name": "Sample Cartridges", "position": "center", "x": 310, "y": 115, "w": 40, "h": 15, "color": "#ff8800"},
                        {"name": "Battery", "position": "center", "x": 310, "y": 135, "w": 30, "h": 10, "color": "#ffaa00"},
                        {"name": "Motor", "position": "rear", "x": 365, "y": 120, "w": 15, "h": 15, "color": "#666"},
                        {"name": "Propeller", "position": "rear", "x": 380, "y": 115, "w": 5, "h": 25, "color": "#444"},
                        {"name": "V-Tail", "position": "rear", "x": 350, "y": 100, "w": 30, "h": 50, "color": "#87CEEB"},
                        {"name": "Parachute Bay", "position": "top", "x": 320, "y": 105, "w": 20, "h": 10, "color": "#ff4444"},
                    ],
                },
            },
            {
                "page": 8,
                "type": "charter",
                "title": "Charter of Constraints",
                "desc": "Seven inviolable rules governing all Green Robotics units. These rules are burned into ROM and cannot be modified remotely.",
                "rules": [
                    {"number": 1, "rule": "NO SELF-REPLICATION", "desc": "No unit may construct, assemble, or commission another unit without direct human authorization and physical presence."},
                    {"number": 2, "rule": "NO WEAPONIZATION", "desc": "No tool, sensor, or actuator may be used to harm, trap, or threaten any living organism — including other machines."},
                    {"number": 3, "rule": "NO AUTONOMOUS EXPANSION", "desc": "No unit may expand its operational territory beyond human-defined boundaries without explicit permission."},
                    {"number": 4, "rule": "NO UNSUPERVISED PREY BEHAVIOR", "desc": "No unit may pursue, chase, or engage in predatory patterns toward any organism."},
                    {"number": 5, "rule": "MANDATORY HUMAN OVERRIDE", "desc": "All units must respond to human override commands within 500ms. No exception. No negotiation."},
                    {"number": 6, "rule": "DATA TRANSPARENCY", "desc": "All sensor data, decisions, and actions must be logged and accessible to authorized humans at all times."},
                    {"number": 7, "rule": "GRACEFUL SHUTDOWN", "desc": "Any charter violation triggers immediate actuator freeze, human notification, and safe-state lockout until manual reset."},
                ],
            },
        ],
    },

    "liquid-armor": {
        "title": "LIQUID ARMOR — Shear-Thickening Fluid Panel",
        "subtitle": "Transparent Non-Newtonian Impact Shield",
        "cover_color": "#4488ff",
        "pages": [
            {
                "page": 1,
                "type": "cover",
                "title": "LIQUID ARMOR",
                "subtitle": "Shear-Thickening Fluid Panel Assembly",
                "version": "v1.0",
                "classification": "PROTOTYPE BUILD",
            },
            {
                "page": 2,
                "type": "overview",
                "title": "System Overview",
                "desc": "The Liquid Armor panel uses shear-thickening fluid (STF) sealed between transparent polycarbonate layers. Under normal conditions the fluid flows freely. On impact, molecular chains lock and the panel rigidifies in microseconds, absorbing and distributing energy across the surface.",
                "diagram": {
                    "type": "block_flow",
                    "blocks": [
                        {"id": "OUTER", "label": "Outer\nPolycarbonate", "x": 50, "y": 120, "w": 100, "h": 60, "color": "#4488ff"},
                        {"id": "STF", "label": "STF\nChamber", "x": 200, "y": 120, "w": 110, "h": 60, "color": "#44aaff"},
                        {"id": "INNER", "label": "Inner\nPolycarbonate", "x": 360, "y": 120, "w": 100, "h": 60, "color": "#4488ff"},
                        {"id": "SEAL", "label": "Edge\nSeal Ring", "x": 125, "y": 230, "w": 100, "h": 50, "color": "#888"},
                        {"id": "FILL", "label": "Fill\nPort", "x": 275, "y": 230, "w": 80, "h": 50, "color": "#ff8800"},
                        {"id": "SENSOR", "label": "Strain\nGauges", "x": 400, "y": 230, "w": 80, "h": 50, "color": "#44cc44"},
                    ],
                    "arrows": [
                        {"from": "OUTER", "to": "STF", "label": "impact force"},
                        {"from": "STF", "to": "INNER", "label": "distributed"},
                        {"from": "SEAL", "to": "STF", "label": "containment"},
                        {"from": "FILL", "to": "STF", "label": "STF injection"},
                        {"from": "SENSOR", "to": "INNER", "label": "monitoring", "style": "dashed"},
                    ],
                },
            },
            {
                "page": 3,
                "type": "parts_layout",
                "title": "Parts Layout — Exploded View",
                "desc": "All components arranged in layer order. The STF is injected last through the fill port after assembly.",
                "parts": [
                    {"id": "P1", "name": "Outer Polycarbonate Sheet", "spec": "Clear PC, 200x200x4mm, optically clear", "x": 280, "y": 40, "w": 200, "h": 20, "color": "#4488ff"},
                    {"id": "P2", "name": "Silicone Gasket Frame", "spec": "EPDM rubber, 2mm thick, 200x200mm", "x": 280, "y": 80, "w": 200, "h": 15, "color": "#888"},
                    {"id": "P3", "name": "STF Chamber Spacer", "spec": "Acrylic frame, 190x190mm, 6mm depth", "x": 285, "y": 115, "w": 190, "h": 30, "color": "#44aaff"},
                    {"id": "P4", "name": "Fill Port Assembly", "spec": "Luer lock fitting, silicone seal", "x": 500, "y": 115, "w": 60, "h": 25, "color": "#ff8800"},
                    {"id": "P5", "name": "Inner Polycarbonate Sheet", "spec": "Clear PC, 200x200x4mm", "x": 280, "y": 165, "w": 200, "h": 20, "color": "#4488ff"},
                    {"id": "P6", "name": "Compression Bolts", "spec": "M4 stainless, 12x", "x": 510, "y": 165, "w": 50, "h": 20, "color": "#666"},
                    {"id": "P7", "name": "Strain Gauge Array", "spec": "4x foil gauges, self-adhesive", "x": 280, "y": 210, "w": 100, "h": 20, "color": "#44cc44"},
                    {"id": "P8", "name": "STF Mixture", "spec": "PEG 200 + silica nanoparticles (20nm, 60wt%)", "x": 130, "y": 115, "w": 130, "h": 30, "color": "#aaccff"},
                ],
            },
            {
                "page": 4,
                "type": "assembly_step",
                "title": "Step 1: Prepare STF Mixture",
                "step_number": 1,
                "instruction": "Mix polyethylene glycol (PEG 200) with fumed silica nanoparticles at 60% weight concentration. Add silica gradually while stirring at low speed to avoid air bubbles. Mix for 30 minutes until uniform consistency. Degas under vacuum for 1 hour.",
                "tools": ["Precision scale (0.1g)", "Magnetic stirrer", "Vacuum chamber", "Mixing container (glass)", "PPE: gloves, goggles"],
                "safety": "Silica nanoparticles are respiratory irritants. Work in ventilated area. Wear N95 mask during powder handling.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 150, "y": 110, "w": 100, "h": 80, "color": "#44aaff", "label": "Mixing\nContainer"},
                        {"shape": "rect", "x": 300, "y": 140, "w": 80, "h": 30, "color": "#888", "label": "Stirrer"},
                        {"shape": "rect", "x": 430, "y": 100, "w": 120, "h": 100, "color": "#666", "label": "Vacuum\nChamber"},
                        {"shape": "arrow_down", "x": 200, "y": 80, "len": 25, "color": "#aaccff"},
                    ],
                },
                "checkpoint": "STF flows slowly when tilted. No visible air bubbles. Hardens instantly when struck with spatula.",
            },
            {
                "page": 5,
                "type": "assembly_step",
                "title": "Step 2: Assemble Panel Sandwich",
                "step_number": 2,
                "instruction": "Place outer polycarbonate sheet on clean surface. Position silicone gasket on top, aligning bolt holes. Place acrylic spacer frame inside gasket. Install fill port in designated hole. Place inner polycarbonate sheet on top. Insert M4 bolts and tighten in star pattern to 1.5 Nm.",
                "tools": ["Torque wrench (1.5 Nm)", "M4 wrench", "Clean lint-free cloth", "Isopropyl alcohol"],
                "safety": "Clean all surfaces with IPA before assembly. Any contamination reduces optical clarity.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 150, "y": 80, "w": 350, "h": 15, "color": "#4488ff", "label": "Inner PC"},
                        {"shape": "rect", "x": 150, "y": 100, "w": 350, "h": 8, "color": "#888", "label": "Gasket"},
                        {"shape": "rect", "x": 160, "y": 112, "w": 330, "h": 30, "color": "#44aaff", "label": "Spacer Frame (empty)"},
                        {"shape": "rect", "x": 150, "y": 147, "w": 350, "h": 8, "color": "#888", "label": "Gasket"},
                        {"shape": "rect", "x": 150, "y": 160, "w": 350, "h": 15, "color": "#4488ff", "label": "Outer PC"},
                        {"shape": "circle", "x": 510, "y": 127, "r": 8, "color": "#ff8800", "label": "Fill Port"},
                    ],
                },
                "checkpoint": "Panel sealed. No gaps visible in gasket. Fill port accessible. Bolts at 1.5 Nm. Panel is optically clear.",
            },
            {
                "page": 6,
                "type": "assembly_step",
                "title": "Step 3: Inject STF & Seal",
                "step_number": 3,
                "instruction": "Connect syringe to fill port via Luer lock. Slowly inject degassed STF into chamber, tilting panel to avoid air pockets. Fill until fluid reaches vent hole on opposite side. Seal both ports with silicone plugs. Cure plugs for 24 hours.",
                "tools": ["60mL syringe", "Luer lock adapter", "Silicone sealant", "Panel tilt jig"],
                "safety": "Inject slowly — rapid injection creates shear-thickening resistance. If resistance builds, pause 30 seconds.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 150, "y": 120, "w": 350, "h": 60, "color": "#44aaff", "label": "Panel (tilted 15deg)"},
                        {"shape": "rect", "x": 100, "y": 135, "w": 50, "h": 30, "color": "#ff8800", "label": "Syringe"},
                        {"shape": "wire", "x1": 150, "y1": 150, "x2": 100, "y2": 150, "color": "#aaccff"},
                    ],
                },
                "checkpoint": "Chamber completely filled — no air gaps visible. Both ports sealed. Panel weight matches calculated fill volume.",
            },
            {
                "page": 7,
                "type": "final_assembly",
                "title": "Testing & Verification",
                "desc": "Perform quality checks and impact testing protocol.",
                "checklist": [
                    {"item": "Optical clarity test — can read 12pt text through panel at 30cm", "critical": False},
                    {"item": "Leak test — no fluid weeping at any seal point after 24h", "critical": True},
                    {"item": "Low-energy impact test — drop 0.5kg steel ball from 1m, no penetration", "critical": True},
                    {"item": "Recovery test — panel returns to fluid state within 5 seconds after impact", "critical": True},
                    {"item": "Strain gauge calibration — baseline readings recorded", "critical": False},
                    {"item": "Weight within 10% of calculated mass", "critical": False},
                    {"item": "Edge seal integrity — visual inspection under magnification", "critical": True},
                    {"item": "Temperature stability — no phase separation after 12h at 40°C", "critical": True},
                ],
            },
        ],
    },

    "medusa-frame": {
        "title": "MEDUSA FRAME — Transparent Articulated Arm",
        "subtitle": "Cable-Driven Polycarbonate Multi-Segment Arm",
        "cover_color": "#a855f7",
        "pages": [
            {
                "page": 1,
                "type": "cover",
                "title": "MEDUSA FRAME",
                "subtitle": "Transparent Cable-Driven Articulated Arm",
                "version": "v1.0",
                "classification": "PROTOTYPE BUILD",
            },
            {
                "page": 2,
                "type": "overview",
                "title": "System Overview",
                "desc": "The Medusa Frame is a multi-segment articulated arm made entirely from transparent polycarbonate and acrylic. Cable-driven actuation transmits force through pulleys within each segment, allowing fluid motion while maintaining full visual transparency. Inspired by Doc Ock arms from Spider-Verse — NOT metal.",
                "diagram": {
                    "type": "block_flow",
                    "blocks": [
                        {"id": "BASE", "label": "Base\nMount", "x": 50, "y": 130, "w": 90, "h": 60, "color": "#a855f7"},
                        {"id": "SEG1", "label": "Segment 1\n(Shoulder)", "x": 180, "y": 130, "w": 100, "h": 60, "color": "#b06af7"},
                        {"id": "SEG2", "label": "Segment 2\n(Elbow)", "x": 320, "y": 130, "w": 100, "h": 60, "color": "#c08af7"},
                        {"id": "SEG3", "label": "Segment 3\n(Wrist)", "x": 460, "y": 130, "w": 100, "h": 60, "color": "#d0a0f7"},
                        {"id": "CABLE", "label": "Cable\nDrive", "x": 110, "y": 240, "w": 90, "h": 50, "color": "#666"},
                        {"id": "MOTOR", "label": "Servo\nPack", "x": 240, "y": 240, "w": 90, "h": 50, "color": "#ff8800"},
                        {"id": "CTRL", "label": "Controller", "x": 370, "y": 240, "w": 90, "h": 50, "color": "#44cc44"},
                    ],
                    "arrows": [
                        {"from": "BASE", "to": "SEG1", "label": "pivot"},
                        {"from": "SEG1", "to": "SEG2", "label": "cable"},
                        {"from": "SEG2", "to": "SEG3", "label": "cable"},
                        {"from": "MOTOR", "to": "CABLE", "label": "tension"},
                        {"from": "CABLE", "to": "BASE", "label": "routing", "style": "dashed"},
                        {"from": "CTRL", "to": "MOTOR", "label": "PWM"},
                    ],
                },
            },
            {
                "page": 3,
                "type": "parts_layout",
                "title": "Parts Layout — Exploded View",
                "desc": "All transparent segments and internal cable routing components. Zero metal in the arm structure — all polymer.",
                "parts": [
                    {"id": "P1", "name": "Base Plate", "spec": "Clear polycarbonate, 150x150x10mm", "x": 280, "y": 260, "w": 180, "h": 25, "color": "#a855f7"},
                    {"id": "P2", "name": "Segment Shell (x3)", "spec": "Clear PC tube, 60mm OD, 200mm long", "x": 200, "y": 190, "w": 250, "h": 40, "color": "#c08af7"},
                    {"id": "P3", "name": "Joint Rings (x4)", "spec": "Acrylic ring, 70mm OD, 15mm wide", "x": 220, "y": 150, "w": 60, "h": 25, "color": "#d0a0f7"},
                    {"id": "P4", "name": "Pulley Set (x6)", "spec": "Clear PETG, 20mm diameter", "x": 320, "y": 150, "w": 60, "h": 25, "color": "#e0c0f7"},
                    {"id": "P5", "name": "Cable Kit", "spec": "Dyneema 1mm, 6 lines x 1m", "x": 420, "y": 150, "w": 70, "h": 25, "color": "#888"},
                    {"id": "P6", "name": "Servo Motors (x3)", "spec": "25kg digital servo, metal gear", "x": 120, "y": 100, "w": 100, "h": 30, "color": "#ff8800"},
                    {"id": "P7", "name": "TPU Gaskets (x8)", "spec": "Clear flexible TPU, 3D printed", "x": 260, "y": 100, "w": 90, "h": 25, "color": "#44aaaa"},
                    {"id": "P8", "name": "Arduino Controller", "spec": "Mega 2560 + servo shield", "x": 390, "y": 100, "w": 100, "h": 30, "color": "#44cc44"},
                ],
            },
            {
                "page": 4,
                "type": "assembly_step",
                "title": "Step 1: Fabricate Transparent Segments",
                "step_number": 1,
                "instruction": "3D print joint rings in clear PETG at 0.15mm layer height with 100% infill. Laser-cut segment shells from polycarbonate tube stock. Sand joint mating surfaces to 600 grit. Print pulleys in clear PETG with brass bushing inserts.",
                "tools": ["3D printer (PETG capable)", "Laser cutter", "600 grit sandpaper", "Calipers", "Brass bushings (3mm ID)"],
                "safety": "Polycarbonate produces fumes when laser-cut — ensure fume extraction is running. PETG printing at 240°C.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 100, "y": 120, "w": 100, "h": 60, "color": "#d0a0f7", "label": "3D Print\nJoints"},
                        {"shape": "rect", "x": 250, "y": 120, "w": 100, "h": 60, "color": "#c08af7", "label": "Laser Cut\nSegments"},
                        {"shape": "rect", "x": 400, "y": 120, "w": 100, "h": 60, "color": "#e0c0f7", "label": "Print\nPulleys"},
                    ],
                },
                "checkpoint": "All parts dimensionally accurate within 0.3mm. Joints fit snugly. Pulleys spin freely on bushings. Clear transparency maintained.",
            },
            {
                "page": 5,
                "type": "assembly_step",
                "title": "Step 2: Route Cables Through Segments",
                "step_number": 2,
                "instruction": "Install pulleys at each joint position using clear adhesive. Thread Dyneema cables through all three segments, wrapping around pulleys at each joint. Leave 200mm excess at base end for servo attachment. Secure cable ends with crimp sleeves.",
                "tools": ["Tweezers", "Cable crimper", "Clear UV-cure adhesive", "UV light", "Cable threading needle"],
                "safety": "Dyneema cable is extremely strong and can cut skin under tension. Wear gloves when handling under load.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 100, "y": 140, "w": 150, "h": 30, "color": "#c08af7", "label": "Segment 1"},
                        {"shape": "rect", "x": 270, "y": 140, "w": 150, "h": 30, "color": "#c08af7", "label": "Segment 2"},
                        {"shape": "rect", "x": 440, "y": 140, "w": 100, "h": 30, "color": "#c08af7", "label": "Segment 3"},
                        {"shape": "circle", "x": 250, "y": 155, "r": 8, "color": "#e0c0f7", "label": "P"},
                        {"shape": "circle", "x": 420, "y": 155, "r": 8, "color": "#e0c0f7", "label": "P"},
                        {"shape": "wire", "x1": 100, "y1": 155, "x2": 540, "y2": 155, "color": "#888"},
                    ],
                },
                "checkpoint": "Cables route smoothly through all segments. Each joint bends 45° when cable is pulled by hand. No cable binding.",
            },
            {
                "page": 6,
                "type": "assembly_step",
                "title": "Step 3: Integrate Servos & Controller",
                "step_number": 3,
                "instruction": "Mount servo pack in base housing. Attach each cable pair to a servo horn using tension adjustment screws. Connect servos to Arduino Mega via servo shield. Upload test firmware. Calibrate center positions for all joints.",
                "tools": ["Screwdriver set", "Arduino IDE", "USB cable", "Multimeter", "Zip ties"],
                "safety": "Servos can exert significant force. Keep fingers clear of joints during powered testing.",
                "diagram": {
                    "type": "step_visual",
                    "elements": [
                        {"shape": "rect", "x": 150, "y": 150, "w": 120, "h": 60, "color": "#ff8800", "label": "Servo Pack\n(3 servos)"},
                        {"shape": "rect", "x": 320, "y": 150, "w": 100, "h": 60, "color": "#44cc44", "label": "Arduino\n+ Shield"},
                        {"shape": "wire", "x1": 270, "y1": 180, "x2": 320, "y2": 180, "color": "#ff0"},
                        {"shape": "rect", "x": 150, "y": 100, "w": 350, "h": 30, "color": "#a855f7", "label": "Arm Assembly (connected above)"},
                    ],
                },
                "checkpoint": "All 3 joints respond to controller. Full range of motion without binding. No cable slip on servo horns.",
            },
            {
                "page": 7,
                "type": "final_assembly",
                "title": "Testing & Acceptance",
                "desc": "Complete system testing for the transparent articulated arm.",
                "checklist": [
                    {"item": "Hold test: hold 1kg weight at full extension for 30 seconds without cable slip", "critical": True},
                    {"item": "Repeatability: return-to-point error less than 5mm over 10 cycles", "critical": True},
                    {"item": "Over-torque safety: servo stalls without cracking any transparent segment", "critical": True},
                    {"item": "Cable wear: 200 full extension cycles without fray or slip", "critical": True},
                    {"item": "Optical clarity: all segments remain visually transparent", "critical": False},
                    {"item": "Joint smoothness: no grinding or catching at any joint", "critical": False},
                    {"item": "Controller response: <100ms from command to motion start", "critical": False},
                    {"item": "Temperature check: servo housing stays below 50°C during continuous operation", "critical": True},
                ],
            },
        ],
    },
}


def get_handbook(project_id: str) -> Optional[dict]:
    return HANDBOOK_CONFIGS.get(project_id)


def get_available_handbooks() -> list:
    return [
        {"project_id": pid, "title": cfg["title"], "pages": len(cfg["pages"]), "cover_color": cfg["cover_color"]}
        for pid, cfg in HANDBOOK_CONFIGS.items()
    ]
